name: Check

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/base

      - run: pnpm markdownlint --ignore-path .gitignore ./**/*.md

      - run: pnpm oxfmt --check --no-error-on-unmatched-pattern .

      - run: pnpm oxlint --type-aware

      - run: pnpm knip --cache --cache-location .knipcache

      - run: pnpm cspell lint --no-progress --gitignore --show-context --cache ./**/*

      - run: pnpm type-check

      - run: pnpm test
        env:
          SIGNET_API_KEY: ${{ secrets.SIGNET_API_KEY }}
          SIGNET_API_SECRET: ${{ secrets.SIGNET_API_SECRET }}
          SIGNET_API_PASSPHRASE: ${{ secrets.SIGNET_API_PASSPHRASE }}
