name: Publish & Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - package.json
      - src/**
      - .github/workflows/publish.yml

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      contents: write
      id-token: write # npm provenance / trusted publishing
    outputs:
      type: ${{ steps.publish.outputs.type }}
      version: ${{ steps.publish.outputs.version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/base

      - run: pnpm build

      - id: publish
        name: Publish to npm
        uses: JS-DevTools/npm-publish@0fd2f4369c5d6bcfcde6091a7c527d810b9b5c3f # v4.1.5
        with:
          provenance: true

      - name: Create release tag
        if: ${{ steps.publish.outputs.type }}
        run: |
          git tag "v${{ steps.publish.outputs.version }}"
          git push origin "v${{ steps.publish.outputs.version }}"

  release-notes:
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ needs.publish.outputs.type }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Create GitHub release
        run: gh release create "v${{ needs.publish.outputs.version }}" --title "v${{ needs.publish.outputs.version }}" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
